                                                                                                                                                                                                                                                                
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE [dbo].[__EFMigrationsHistory] ([MigrationId] nvarchar(300) NOT NULL,[ProductVersion] nvarchar(64) NOT NULL);                                                                                                                                    
CREATE TABLE [dbo].[Addresses] ([Id] int NOT NULL,[UserId] int NOT NULL,[FullName] nvarchar(MAX) NULL,[Phone] nvarchar(MAX) NULL,[Province] nvarchar(MAX) NULL,[District] nvarchar(MAX) NULL,[Ward] nvarchar(MAX) NULL,[Street] nvarchar(MAX) NULL,[IsD
CREATE TABLE [dbo].[AddressesNew] ([Id] int NOT NULL,[CustomerId] int NOT NULL,[FullName] nvarchar(400) NULL,[Phone] nvarchar(100) NULL,[Province] nvarchar(200) NULL,[District] nvarchar(200) NULL,[Ward] nvarchar(200) NULL,[Street] nvarchar(400) NUL
CREATE TABLE [dbo].[AspNetRoleClaims] ([Id] int NOT NULL,[RoleId] nvarchar(900) NOT NULL,[ClaimType] nvarchar(MAX) NULL,[ClaimValue] nvarchar(MAX) NULL);                                                                                                  
CREATE TABLE [dbo].[AspNetRoles] ([Id] nvarchar(900) NOT NULL,[Name] nvarchar(512) NULL,[NormalizedName] nvarchar(512) NULL,[ConcurrencyStamp] nvarchar(MAX) NULL);                                                                                        
CREATE TABLE [dbo].[AspNetUserClaims] ([Id] int NOT NULL,[UserId] nvarchar(900) NOT NULL,[ClaimType] nvarchar(MAX) NULL,[ClaimValue] nvarchar(MAX) NULL);                                                                                                  
CREATE TABLE [dbo].[AspNetUserLogins] ([LoginProvider] nvarchar(900) NOT NULL,[ProviderKey] nvarchar(900) NOT NULL,[ProviderDisplayName] nvarchar(MAX) NULL,[UserId] nvarchar(900) NOT NULL);                                                              
CREATE TABLE [dbo].[AspNetUserRoles] ([UserId] nvarchar(900) NOT NULL,[RoleId] nvarchar(900) NOT NULL);                                                                                                                                                      
CREATE TABLE [dbo].[AspNetUsers] ([Id] nvarchar(900) NOT NULL,[UserName] nvarchar(512) NULL,[NormalizedUserName] nvarchar(512) NULL,[Email] nvarchar(512) NULL,[NormalizedEmail] nvarchar(512) NULL,[EmailConfirmed] bit NOT NULL,[PasswordHash] nvarchar
CREATE TABLE [dbo].[AspNetUserTokens] ([UserId] nvarchar(900) NOT NULL,[LoginProvider] nvarchar(900) NOT NULL,[Name] nvarchar(900) NOT NULL,[Value] nvarchar(MAX) NULL);                                                                                   
CREATE TABLE [dbo].[AttributeValues] ([ValueId] int NOT NULL,[AttributeId] int NULL,[Value] nvarchar(400) NULL);                                                                                                                                            
CREATE TABLE [dbo].[Banners] ([BannerId] int NOT NULL,[Title] nvarchar(510) NULL,[ImageUrl] nvarchar(1000) NULL,[LinkUrl] nvarchar(1000) NULL,[Position] nvarchar(200) NULL,[IsActive] bit NOT NULL);                                                    
CREATE TABLE [dbo].[BlogCategories] ([Id] int NOT NULL,[Name] nvarchar(400) NOT NULL,[Slug] nvarchar(510) NULL);                                                                                                                                            
CREATE TABLE [dbo].[Blogs] ([Id] int NOT NULL,[Title] nvarchar(600) NOT NULL,[Slug] nvarchar(600) NOT NULL,[Content] nvarchar(MAX) NOT NULL,[Thumbnail] nvarchar(1000) NULL,[CategoryId] int NOT NULL,[Status] int NOT NULL,[CreatedDate] datetime2 NOT 
CREATE TABLE [dbo].[Brands] ([BrandId] int NOT NULL,[BrandName] nvarchar(510) NOT NULL,[LogoUrl] nvarchar(1000) NULL,[Description] nvarchar(MAX) NULL);                                                                                                    
CREATE TABLE [dbo].[CartItems] ([CartItemId] int NOT NULL,[CartId] int NOT NULL,[ProductVariantId] int NOT NULL,[Quantity] int NOT NULL,[Price] decimal NOT NULL);                                                                                        
CREATE TABLE [dbo].[Carts] ([CartId] int NOT NULL,[CustomerId] int NULL,[CreatedDate] datetime2 NOT NULL,[UserId] nvarchar(MAX) NOT NULL);                                                                                                                 
CREATE TABLE [dbo].[Categories] ([CategoryId] int NOT NULL,[CategoryName] nvarchar(400) NOT NULL,[Slug] nvarchar(510) NULL,[ParentId] int NULL,[Description] nvarchar(MAX) NULL,[ImageUrl] nvarchar(1000) NULL);                                         
CREATE TABLE [dbo].[Coupons] ([Id] int NOT NULL,[Code] nvarchar(100) NOT NULL,[DiscountValue] decimal NOT NULL,[DiscountType] nvarchar(40) NOT NULL,[MinOrderValue] decimal NULL,[UsageLimit] int NOT NULL,[UsedCount] int NOT NULL,[ExpiryDate] datetim
CREATE TABLE [dbo].[Custom_Wishlists] ([Id] int NOT NULL,[UserId] int NOT NULL,[ProductId] int NOT NULL,[CreatedAt] datetime NULL);                                                                                                                        
CREATE TABLE [dbo].[CustomerAddresses] ([Id] int NOT NULL,[CustomerId] int NOT NULL,[FullName] nvarchar(400) NOT NULL,[Phone] nvarchar(100) NOT NULL,[Address] nvarchar(1000) NOT NULL,[IsDefault] bit NOT NULL);                                        
CREATE TABLE [dbo].[Customers] ([CustomerId] int NOT NULL,[UserId] nvarchar(MAX) NULL,[FullName] nvarchar(400) NOT NULL,[Email] nvarchar(510) NULL,[Phone] nvarchar(100) NULL,[Address] nvarchar(1000) NULL,[AvatarUrl] nvarchar(MAX) NULL,[CreatedDate]
CREATE TABLE [dbo].[InventoryTransactions] ([TransactionId] int NOT NULL,[ProductVariantId] int NULL,[Quantity] int NOT NULL,[TransactionType] nvarchar(100) NOT NULL,[TransactionDate] datetime2 NOT NULL,[Note] nvarchar(MAX) NULL);                   
CREATE TABLE [dbo].[MotorbikeModels] ([ModelId] int NOT NULL,[ModelName] nvarchar(400) NOT NULL,[Manufacturer] nvarchar(400) NULL,[ParentId] int NULL);                                                                                                    
CREATE TABLE [dbo].[Notifications] ([Id] int NOT NULL,[UserId] nvarchar(MAX) NOT NULL,[Title] nvarchar(510) NOT NULL,[Message] nvarchar(MAX) NOT NULL,[IsRead] bit NOT NULL,[CreatedDate] datetime2 NOT NULL);                                           
CREATE TABLE [dbo].[OrderItems] ([OrderItemId] int NOT NULL,[OrderId] int NULL,[ProductVariantId] int NULL,[Quantity] int NOT NULL,[Price] decimal NOT NULL);                                                                                             
CREATE TABLE [dbo].[Orders] ([OrderId] int NOT NULL,[OrderCode] nvarchar(16) NULL,[CustomerId] int NULL,[StoreId] int NULL,[CreatedByStaffId] int NULL,[CouponId] int NULL,[ShippingMethodId] int NULL,[OrderDate] datetime2 NOT NULL,[TotalAmount] dec
CREATE TABLE [dbo].[OrderStatusHistories] ([HistoryId] int NOT NULL,[OrderId] int NULL,[Status] nvarchar(200) NULL,[ChangedDate] datetime2 NOT NULL);                                                                                                      
CREATE TABLE [dbo].[Payments] ([PaymentId] int NOT NULL,[OrderId] int NULL,[PaymentMethod] nvarchar(200) NULL,[PaymentStatus] nvarchar(200) NULL,[PaidDate] datetime2 NULL);                                                                              
CREATE TABLE [dbo].[ProductAttributes] ([AttributeId] int NOT NULL,[AttributeName] nvarchar(400) NOT NULL);                                                                                                                                                  
CREATE TABLE [dbo].[ProductImages] ([ImageId] int NOT NULL,[ProductId] int NULL,[ImageUrl] nvarchar(1000) NOT NULL,[IsPrimary] bit NOT NULL,[DisplayOrder] int NOT NULL);                                                                                 
CREATE TABLE [dbo].[ProductReviews] ([ReviewId] int NOT NULL,[ProductId] int NULL,[ProductVariantId] int NULL,[CustomerId] int NULL,[Rating] int NOT NULL,[Comment] nvarchar(MAX) NULL,[CreatedDate] datetime2 NOT NULL,[Status] nvarchar(40) NOT NULL)
CREATE TABLE [dbo].[Products] ([ProductId] int NOT NULL,[CategoryId] int NULL,[BrandId] int NULL,[ProductName] nvarchar(600) NOT NULL,[Slug] nvarchar(510) NULL,[Description] nvarchar(MAX) NULL,[IsFeatured] bit NOT NULL,[IsActive] bit NOT NULL,[Cre
CREATE TABLE [dbo].[ProductVariantAttributeValue] ([Id] int NOT NULL,[ProductVariantId] int NOT NULL,[ValueId] int NOT NULL);                                                                                                                               
CREATE TABLE [dbo].[ProductVariants] ([ProductVariantId] int NOT NULL,[ProductId] int NULL,[BaseUnitId] int NULL,[ModelId] int NULL,[SKU] nvarchar(200) NULL,[VariantName] nvarchar(510) NOT NULL,[Price] decimal NOT NULL,[OriginalPrice] decimal NULL,
CREATE TABLE [dbo].[PromotionProducts] ([Id] int NOT NULL,[PromotionId] int NOT NULL,[ProductId] int NOT NULL);                                                                                                                                             
CREATE TABLE [dbo].[Promotions] ([PromotionId] int NOT NULL,[PromotionName] nvarchar(510) NOT NULL,[Description] nvarchar(MAX) NULL,[DiscountType] nvarchar(40) NOT NULL,[DiscountPercentage] decimal NOT NULL,[DiscountAmount] decimal NOT NULL,[MinOrde
CREATE TABLE [dbo].[ServiceBookings] ([BookingId] int NOT NULL,[BookingCode] nvarchar(16) NULL,[CustomerId] int NULL,[ServiceId] int NULL,[CreatedByStaffId] int NULL,[AssignedStaffId] int NULL,[BookingDate] datetime2 NOT NULL,[ServiceDate] datetime
CREATE TABLE [dbo].[ServiceComboItems] ([Id] int NOT NULL,[ComboId] int NOT NULL,[ServiceId] int NOT NULL);                                                                                                                                                 
CREATE TABLE [dbo].[ServiceCombos] ([ComboId] int NOT NULL,[ComboName] nvarchar(400) NOT NULL,[TotalPrice] decimal NOT NULL,[DiscountPrice] decimal NOT NULL,[Description] nvarchar(MAX) NULL,[ImageUrl] nvarchar(1000) NULL,[IsActive] bit NULL);      
CREATE TABLE [dbo].[Services] ([ServiceId] int NOT NULL,[ServiceName] nvarchar(400) NOT NULL,[Price] decimal NOT NULL,[Description] nvarchar(MAX) NULL,[ImageUrl] nvarchar(1000) NULL,[IsActive] bit NOT NULL);                                          
CREATE TABLE [dbo].[ShippingMethods] ([Id] int NOT NULL,[Name] nvarchar(200) NOT NULL,[Description] nvarchar(MAX) NULL,[Cost] decimal NOT NULL,[EstimatedDays] nvarchar(200) NULL,[IsActive] bit NOT NULL);                                              
CREATE TABLE [dbo].[Sliders] ([SliderId] int NOT NULL,[Title] nvarchar(510) NULL,[ImageUrl] nvarchar(1000) NULL,[LinkUrl] nvarchar(1000) NULL,[Position] int NOT NULL,[IsActive] bit NOT NULL);                                                          
CREATE TABLE [dbo].[Staffs] ([StaffId] int NOT NULL,[UserId] nvarchar(MAX) NULL,[StoreId] int NULL,[StaffCode] nvarchar(100) NOT NULL,[Position] nvarchar(200) NULL,[CreatedDate] datetime2 NOT NULL);                                                   
CREATE TABLE [dbo].[Stores] ([StoreId] int NOT NULL,[StoreName] nvarchar(400) NOT NULL,[Address] nvarchar(1000) NULL,[Phone] nvarchar(100) NULL);                                                                                                          
CREATE TABLE [dbo].[StoreSettings] ([SettingID] int NOT NULL,[StoreName] nvarchar(510) NOT NULL,[LogoUrl] nvarchar(1000) NULL,[Phone] nvarchar(100) NULL,[Email] nvarchar(200) NULL,[Address] nvarchar(MAX) NULL,[Facebook] nvarchar(510) NULL,[Zalo] nv
CREATE TABLE [dbo].[Units] ([UnitId] int NOT NULL,[UnitName] nvarchar(100) NOT NULL,[Symbol] nvarchar(40) NULL);                                                                                                                                            
CREATE TABLE [dbo].[Wishlist] ([WishlistId] int NOT NULL,[CustomerId] int NULL,[CreatedDate] datetime2 NOT NULL);                                                                                                                                           
CREATE TABLE [dbo].[WishlistItem] ([WishlistItemId] int NOT NULL,[WishlistId] int NULL,[ProductId] int NULL,[CreatedDate] datetime2 NOT NULL);                                                                                                             
CREATE TABLE [dbo].[Wishlists] ([Id] int NOT NULL,[UserId] int NOT NULL,[ProductId] int NOT NULL,[CreatedAt] datetime2 NOT NULL);                                                                                                                          
CREATE TABLE [dbo].[WishlistsNew] ([Id] int NOT NULL,[UserId] int NOT NULL,[ProductId] int NOT NULL,[CreatedAt] datetime NULL);                                                                                                                            
